security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
                id: fos_user.user_provider.username
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
              provider: fos_userbundle
              csrf_token_generator: security.csrf.token_manager
            remember_me:
              secret:   '%kernel.secret%'
              lifetime: 31536000 # 1 year in seconds
              path:     /
              always_remember_me: true

            logout:       true
            anonymous:    true

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
            - { path: ^/PracticeExercise, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/ChooseLevel, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/Exercise, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/section, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/MatematicaAritmetica, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/Geometria, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/SendFeedBack, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/ChangeImage, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/success, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/GetRandomTip, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/ChooseLevel, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/VerifyAnswer, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/ChangeBoard, role: [ROLE_ADMIN, ROLE_USER] }
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }